### ISSUE TITLE
RHEL-8

### ISSUE THREAD

**Issue by toracat** [Tronde/poor-man-s-rhel-mirror#3]
Could you extend this to RHEL-8?

**Comment by Tronde** [comment]
Hi,
I have to look into it first, to see what's possible and how things work in RHEL 8. But I'll try building a version for RHEL 8, too.

**Comment by Tronde** [comment]
For reference in official documentation: [Create a local repo with Red Hat Enterprise Linux 8](https://access.redhat.com/solutions/23016#rhel8)

**Comment by toracat** [comment]
Thank you.

**Comment by Tronde** [comment]
Merry Christmas!

It took me six month but on time for Christmas I release [version 3.0.0-beta](https://github.com/Tronde/poor-man-s-rhel-mirror/releases/tag/3.0.0-beta) of the Poor Man's Mirror fit and ready for RHEL 8.

Be aware it's a beta and open for testing. @toracat and everyone else, I would be glad if you would drop some feedback here and let me know if it works before I remove the beta tag.

**Comment by Tronde** [comment]
Since it is over a month without any issue yet, I've released version 3.0.0 and close this one here.
