### ISSUE TITLE
Just a question: What are the 4 stages ?

### ISSUE THREAD

**Issue by linuxdan** [Tronde/poor-man-s-rhel-mirror#5]
In my use case I have four different stages (E, I, Q and P)

My guess is that they are something like Development, Test, QA, and Production.  Is that accurate ?

**Comment by Tronde** [comment]
Ah, I just realized a part of my answer does not belong to the Poor Man's RHEL Mirror.

> But it doesn't matter what or how many stages you use. You could assign your systems to the differen patch phases as you like.

> In our environment most of the Test and Development systems are in patch-phase-1. But I also have colleagues running Production systems and have them assigned to patch-phase-1, because they want to get the patches as soon as possible.

This part of my answer belongs to another project called [Ansible Role RHEL Patchmanagement](https://github.com/Tronde/ansible-role-rhel-patchmanagement).

Sorry for any confusion.
